
global:
  redis:
    password: bhXvm2p7Xj
  kibanaEnabled: false

vergon:
  affinityNotMaster: &affinityNotMaster
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - arpit-server
  topologySpeadConstraints: &topologyRegion
    - topologyKey: "topology.kubernetes.io/region"
      whenUnsatisfiable: "DoNotSchedule"
      maxSkew: 1

redis:
  architecture: standalone
  master:
    kind: Deployment
    persistence:
      enabled: false
    count: 1  #default
    #affinity:
    #  *affinityNotMaster
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

cassandra:
  topologySpreadConstraints:
    *topologyRegion
  replicaCount: 1
  cluster:
    datacenter: datacenter1
    endpointSnitch: GossipingPropertyFileSnitch
    extraSeeds:
      - nand-cassandra-0.nand-cassandra-headless.nand
  dbUser:
    user: cassandra
    password: vergon
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: ""

provisionDataStore:
  elasticsearch: true

elasticsearch:
  image:
    tag: 7.17.5
  extraConfig:
    node.attr.dc: datacenter1
    cluster.routing.allocation.awareness.attributes: dc
  master:
    topologySpreadConstraints:
      *topologyRegion
    replicaCount: 1
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
  data:
    replicaCount: 1
    topologySpreadConstraints:
      *topologyRegion
  ingest:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  security:
    enabled: false
    elasticPassword: password
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

