
global:
  redis:
    password: bhXvm2p7Xj
  kibanaEnabled: false

vergon:
  affinityNotMaster: &affinityNotMaster
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - arpit-server

redis:
  replica:
    replicaCount: 1
    affinity:
      *affinityNotMaster
  master:
    affinity:
      *affinityNotMaster

cassandra:
  dbUser:
    user: cassandra
    password: vergon
  nodeSelector:
    kubernetes.io/hostname: arpit-server

provisionDataStore:
  elasticsearch: true

elasticsearch:
  master:
    masterOnly: false
    replicaCount: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 2
    affinity:
      *affinityNotMaster
  data:
    replicaCount: 0
  ingest:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  security:
    elasticPassword: password

