{
 "title": "Temp Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "service_name", "query": { "query": "label_values(service_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_sum{service_name=\"$service_name\"}[5m]) / rate(http_server_duration_count{service_name=\"$service_name\"}[5m])",
     "legendFormat": "route={{http_route}}, method={{http_method}}, status_code={{http_status_code}}"
    }
   ]
  },
  {
   "title": "Req per sec [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_duration_count{service_name=\"$service_name\"}[5m])",
     "legendFormat": "route={{http_route}}, method={{http_method}}, status_code={{http_status_code}}"
    }
   ]
  },
  {
   "title": "SLO req duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_duration_bucket{service_name=\"$service_name\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}