apiVersion: v2
appVersion: 1.0.0
description: Vergon Kubernetes
name: vergon
type: application
version: 0.0.1
dependencies:
  - name: elasticsearch
    version: ^19.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: provisionDataStore.elasticsearch
  - name: cassandra
    version: ^9.2.11
    repository: https://charts.bitnami.com/bitnami
    condition: provisionDataStore.cassandra
