
global:
  kibanaEnabled: false

vergon:
  affinityNotMaster: &affinityNotMaster
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - arpit-server

cassandra:
  cluster:
    datacenter: nand1
    endpointSnitch: GossipingPropertyFileSnitch
    extraSeeds:
      - vergon-cassandra-0.vergon-cassandra-headless.default
  dbUser:
    user: cassandra
    password: vergon
  nodeSelector:
    topology.kubernetes.io/region: nand
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: ""

provisionDataStore:
  elasticsearch: true
  cassandra: true

elasticsearch:
  image:
    tag: 7.17.5
  extraConfig:
    node.attr.dc: nand1
    cluster.routing.allocation.awareness.attributes: dc
  extraHosts:
    - vergon-elasticsearch-master-hl.default
    - vergon-elasticsearch-data-hl.default
  master:
    masterOnly: false
    replicaCount: 1
    autoscaling:
      minReplicas: 1
      maxReplicas: 2
    nodeSelector:
      topology.kubernetes.io/region: nand
    resources:
      requests:
        cpu: 150m
        memory: 2048Mi
  data:
    replicaCount: 0
  ingest:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  security:
    enabled: false
    elasticPassword: password
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

