apiVersion: v1
kind: Service
metadata:
  name: apiserver
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001
  selector:
    app: apiserver
  type: NodePort