apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
spec:
  selector:
    matchLabels:
      app: apiserver
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
      labels:
        app: apiserver
    spec:
      affinity:
        {{- .Values.vergon.affinityNotMaster | toYaml | nindent 8 }}
      containers:
        - name: apiserver
          image: arpitjindal1997/apiserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
