apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver-deployment
spec:
  selector:
    matchLabels:
      app: apiserver
  replicas: 1
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
        - name: apiserver
          image: arpitjindal1997/apiserver:latest
          ports:
            - containerPort: 8080
