apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: default
  labels:
    app: gateway
spec:
  ports:
    - port: 80
      name: http-web
      protocol: TCP
      targetPort: 80
      nodePort: 30001
  selector:
    app: gateway
  type: NodePort