apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
spec:
  selector:
    matchLabels:
      app: indexer
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
      labels:
        app: indexer
    spec:
      affinity:
        {{- .Values.vergon.affinityNotMaster | toYaml | nindent 8 }}
      containers:
        - name: indexer
          image: arpitjindal1997/indexer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
