apiVersion: v1
kind: Service
metadata:
  name: oidc
  namespace: default
  labels:
    app: oidc
spec:
  ports:
    - port: 9998
      protocol: TCP
      targetPort: 9998
      name: http-web
  selector:
    app: oidc
  type: ClusterIP