apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vergon-refresher
  namespace: default
spec:
  endpoints:
    - honorLabels: true
      path: /metrics
      port: http-web
      scheme: http
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: refresher