apiVersion: v1
kind: Service
metadata:
  name: refresher
  namespace: default
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30002
  selector:
    app: refresher
  type: ClusterIP