apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-deployment
spec:
  selector:
    matchLabels:
      app: tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: tracker
    spec:
      containers:
        - name: tracker
          image: arpitjindal1997/tracker:latest
          ports:
            - containerPort: 1337
