apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker
spec:
  selector:
    matchLabels:
      app: tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: tracker
    spec:
      affinity:
        {{- .Values.vergon.affinityNotMaster | toYaml | nindent 8 }}
      containers:
        - name: tracker
          image: arpitjindal1997/tracker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
