{
 "title": "Go Metrics",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(go_goroutines, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(go_goroutines{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(go_goroutines{namespace=\"$namespace\",pod=\"$pod\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(go_goroutines{namespace=\"$namespace\",pod=\"$pod\",job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{instance=\"$instance\"}",
     "legendFormat": "mspan_inuse"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "mspan_sys"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{instance=\"$instance\"}",
     "legendFormat": "mcache_inuse"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "mcache_sys"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "buck_hash_sys"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "gc_sys"
    },
    {
     "expr": "go_memstats_other_sys_bytes{instance=\"$instance\"} - go_memstats_other_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "other_sys"
    },
    {
     "expr": "go_memstats_next_gc_bytes{instance=\"$instance\"}",
     "legendFormat": "next_gc"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"$instance\"}",
     "legendFormat": "heap_alloc"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "heap_sys"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=\"$instance\"}",
     "legendFormat": "heap_idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"$instance\"}",
     "legendFormat": "heap_inuse"
    },
    {
     "expr": "go_memstats_heap_released_bytes{instance=\"$instance\"}",
     "legendFormat": "heap_released"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=\"$instance\"}",
     "legendFormat": "stack_inuse"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "stack_sys"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{instance=\"$instance\"}",
     "legendFormat": "sys"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{instance=\"$instance\"} - go_memstats_frees_total{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  }
 ]
}