{
 "title": "Redis 1",
 "description": "Redis Dashboard",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_up, namespace)"
    }
   },
   {
    "name": "pod_name",
    "label": "Pod Name",
    "query": {
     "query": "label_values(redis_up{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up{namespace=\"$namespace\", pod=\"$pod_name\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Key Performance Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Health Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_up{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "No of Masters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "redis_instance_info{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Rejected Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(redis_rejected_connections_total{instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Last Backup",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - redis_rdb_last_save_timestamp_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Clients Historical Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_connected_clients{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Command latency per second",
   "type": "timeseries",
   "description": "Average taken across instances",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(redis_commands_duration_seconds_total{instance=~\"$instance\"}[1m])) by (cmd)\n  /\navg(irate(redis_commands_total{instance=~\"$instance\"}[1m])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Memory fragmentation ratio per instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 12 },
   "targets": [
    { "expr": "redis_mem_fragmentation_ratio", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Commands Calls per second",
   "type": "timeseries",
   "description": "Average taken across instances",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) - sum (redis_db_keys_expiring{instance=~\"$instance\"}) ",
     "legendFormat": "Non Expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{instance=~\"$instance\"}) ",
     "legendFormat": "Expiring"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hits / Misses ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Miss ratio per instance",
   "type": "graph",
   "description": "Miss rate shows the percentage of key space lookups that hit a key.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(redis_keyspace_misses_total{instance=~\"$instance\"}[1m]) / (irate(redis_keyspace_hit_total{instance=~\"$instance\"}[1m]) + irate(redis_keyspace_misses_total{instance=~\"$instance\"}[1m]))) by (instance)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "0", "legendFormat": "Target Miss ratio for cache" }
   ]
  },
  {
   "title": "Hit ratio per instance",
   "type": "graph",
   "description": "Hit rate shows the percentage of key space lookups that hit a key.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(redis_keyspace_hits_total{instance=~\"$instance\"}[1m]) / (irate(redis_keyspace_hit_total{instance=~\"$instance\"}[1m]) + irate(redis_keyspace_misses_total{instance=~\"$instance\"}[1m]))) by (instance)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "1", "legendFormat": "Target Hit ratio for cache" }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{instance=~\"$instance\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected slaves by instance",
   "type": "graph",
   "description": "This metric will only be non-zero if the instance is a master",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_slaves{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Connection Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_connections_received_total",
     "legendFormat": "Total Connection Recieved"
    }
   ]
  },
  {
   "title": "Network In & Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Network In "
    },
    {
     "expr": "rate(redis_net_output_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Network Out"
    }
   ]
  },
  {
   "title": "Redis Replication Broken",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(redis_connected_slaves[1m])"
    }
   ]
  },
  {
   "title": "Total Connection Rejected",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(redis_rejected_connections_total[1m])",
     "legendFormat": "Rejected Connection"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "description": "Total taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(redis_memory_used_bytes{instance=~\"$instance\"})",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(redis_memory_max_bytes{instance=~\"$instance\"})",
     "legendFormat": "Configured max memory"
    },
    {
     "expr": "sum(redis_memory_used_rss_bytes{instance=~\"$instance\"})",
     "legendFormat": "Used RSS memory"
    }
   ]
  },
  {
   "title": "Key evictions per second per instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_evicted_keys_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 74 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{instance=~\"$instance\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  }
 ]
}