name: Build Go
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'java-src/**'
      - 'helm-chart/**'
  workflow_dispatch:

jobs:
  Build_Go:
    name: Build Go Projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Stage
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Builder Script
        run: bash ./build/builder.sh
